[package]
name = "xler_native"
version = "0.2.0"
authors = []

[lib]
name = "xler_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.23.0"
lazy_static = "1.4"
calamine = { version = "0.19.0", features = ["dates"] }
